# Generated by Django 5.2.3 on 2026-01-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_propertyimage_is_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_qr_code',
            field=models.BooleanField(default=False, help_text='Mark if this is a QR code image'),
        ),
    ]
